# This file is for the purpose of local development. Start keycloak & db services by running 'docker compose up -d'
# and the urlshortener app from intellij.

version: '3.8'

services:
  db-local:
    build: ./docker-containers/mysql/  # Path to MySQL Dockerfile directory
    container_name: urlshortener-db-local
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    networks:
      - urlshortener-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

  keycloak-local:
    build: ./docker-containers/keycloak/local/  # Path to local Keycloak Dockerfile directory
    container_name: urlshortener-keycloak-local
    ports:
      - "8080:8080"
    networks:
      - urlshortener-network
    depends_on:
      db-local:
        condition: service_healthy
    environment:
      - DB_HOST=db-local  # This will override the hardcoded localhost

networks:
  urlshortener-network:
    driver: bridge
