apiVersion: v1
kind: Service
metadata:
  name: urlshortener-app-service
  namespace: urlshortener-dev
  labels:
    app: urlshortener
    layer: backend
spec:
  ports:
    # todo parameterize ports and namespaces, maybe by helm and env vars?
  - port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 30008
  selector:
    app: urlshortener
    layer: backend
  type: NodePort
