apiVersion: apps/v1
kind: Deployment
metadata:
  name: urlshortener-app-deployment
  labels:
    app: urlshortener
    layer: backend
  namespace: urlshortener-dev
spec:
  template:
    metadata:
      name: urlshortener-app-pod
      labels:
        app: urlshortener
        layer: backend
    spec:
      containers:
        - image: urlshortener-app:k8s
          name: urlshortener-app-container
          resources:
            requests:
              memory: "1Gi"
              cpu: "1"
            limits:
              memory: "2Gi"
              cpu: "2"
          ports:
            - containerPort: 8080
          imagePullPolicy: IfNotPresent
  replicas: 1
  selector:
    matchLabels:
      app: urlshortener
      layer: backend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
